defaults: &defaults
  adapter: mysql2
  host: localhost
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
  pool: 25

development:
  <<: *defaults
  database: ezwebsites_development

test:
  <<: *defaults
  database: ezwebsites_test

production:
  <<: *defaults
  database: ezwebsites_production
  reaping_frequency: 10